In [1]:
import pandas as pd

In [2]:
pd.__version__

'3.0.3'

In [4]:
pd.read_csv("Expanded_data_with_more_features.csv")

,Unnamed: 0,Gender,EthnicGroup,ParentEduc,LunchType,TestPrep,ParentMaritalStatus,PracticeSport,IsFirstChild,NrSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
0,0,female,NaN,bachelor's degree,standard,none,married,regularly,yes,3.0,school_bus,< 5,71,71,74
1,1,female,group C,some college,standard,NaN,married,sometimes,yes,0.0,NaN,5 - 10,69,90,88
2,2,female,group B,master's degree,standard,none,single,sometimes,yes,4.0,school_bus,< 5,87,93,91
3,3,male,group A,associate's degree,free/reduced,none,married,never,no,1.0,NaN,5 - 10,45,56,42
4,4,male,group C,some college,standard,none,married,sometimes,yes,0.0,school_bus,5 - 10,76,78,75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30636,816,female,group D,high school,standard,none,single,sometimes,no,2.0,school_bus,5 - 10,59,61,65
30637,890,male,group E,high school,standard,none,single,regularly,no,1.0,private,5 - 10,58,53,51
30638,911,female,NaN,high school,free/reduced,completed,married,sometimes,no,1.0,private,5 - 10,61,70,67
30639,934,female,group D,associate's degree,standard,completed,married,regularly,no,3.0,school_bus,5 - 10,82,90,93
30640,960,male,group B,some college,standard,none,married,never,no,1.0,school_bus,5 - 10,64,60,58

In [5]:
data=pd.read_csv("Expanded_data_with_more_features.csv")

In [6]:
data

,Unnamed: 0,Gender,EthnicGroup,ParentEduc,LunchType,TestPrep,ParentMaritalStatus,PracticeSport,IsFirstChild,NrSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
0,0,female,NaN,bachelor's degree,standard,none,married,regularly,yes,3.0,school_bus,< 5,71,71,74
1,1,female,group C,some college,standard,NaN,married,sometimes,yes,0.0,NaN,5 - 10,69,90,88
2,2,female,group B,master's degree,standard,none,single,sometimes,yes,4.0,school_bus,< 5,87,93,91
3,3,male,group A,associate's degree,free/reduced,none,married,never,no,1.0,NaN,5 - 10,45,56,42
4,4,male,group C,some college,standard,none,married,sometimes,yes,0.0,school_bus,5 - 10,76,78,75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30636,816,female,group D,high school,standard,none,single,sometimes,no,2.0,school_bus,5 - 10,59,61,65
30637,890,male,group E,high school,standard,none,single,regularly,no,1.0,private,5 - 10,58,53,51
30638,911,female,NaN,high school,free/reduced,completed,married,sometimes,no,1.0,private,5 - 10,61,70,67
30639,934,female,group D,associate's degree,standard,completed,married,regularly,no,3.0,school_bus,5 - 10,82,90,93
30640,960,male,group B,some college,standard,none,married,never,no,1.0,school_bus,5 - 10,64,60,58

In [8]:
data.head(200)

,Unnamed: 0,Gender,EthnicGroup,ParentEduc,LunchType,TestPrep,ParentMaritalStatus,PracticeSport,IsFirstChild,NrSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
0,0,female,NaN,bachelor's degree,standard,none,married,regularly,yes,3.0,school_bus,< 5,71,71,74
1,1,female,group C,some college,standard,NaN,married,sometimes,yes,0.0,NaN,5 - 10,69,90,88
2,2,female,group B,master's degree,standard,none,single,sometimes,yes,4.0,school_bus,< 5,87,93,91
3,3,male,group A,associate's degree,free/reduced,none,married,never,no,1.0,NaN,5 - 10,45,56,42
4,4,male,group C,some college,standard,none,married,sometimes,yes,0.0,school_bus,5 - 10,76,78,75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,209,female,group B,some college,free/reduced,NaN,single,sometimes,no,2.0,NaN,NaN,58,61,66
196,210,male,group D,some high school,free/reduced,completed,widowed,sometimes,yes,3.0,school_bus,< 5,77,77,77
197,211,male,group C,some college,free/reduced,NaN,married,sometimes,yes,3.0,school_bus,5 - 10,35,28,27
198,212,female,group C,high school,free/reduced,none,divorced,sometimes,yes,2.0,school_bus,5 - 10,42,62,60
199,213,male,group C,associate's degree,free/reduced,completed,single,regularly,no,1.0,school_bus,5 - 10,61,51,57

In [9]:
data.tail(200)

,Unnamed: 0,Gender,EthnicGroup,ParentEduc,LunchType,TestPrep,ParentMaritalStatus,PracticeSport,IsFirstChild,NrSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
30441,826,female,group D,some college,standard,none,married,regularly,no,3.0,school_bus,5 - 10,64,63,72
30442,863,male,group B,some college,standard,completed,NaN,NaN,no,3.0,NaN,< 5,69,62,64
30443,865,male,group E,associate's degree,standard,NaN,single,sometimes,no,3.0,school_bus,5 - 10,84,76,73
30444,911,female,group C,some college,free/reduced,none,divorced,never,no,3.0,school_bus,5 - 10,59,66,71
30445,953,male,group B,associate's degree,standard,completed,single,sometimes,no,4.0,school_bus,5 - 10,69,62,68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30636,816,female,group D,high school,standard,none,single,sometimes,no,2.0,school_bus,5 - 10,59,61,65
30637,890,male,group E,high school,standard,none,single,regularly,no,1.0,private,5 - 10,58,53,51
30638,911,female,NaN,high school,free/reduced,completed,married,sometimes,no,1.0,private,5 - 10,61,70,67
30639,934,female,group D,associate's degree,standard,completed,married,regularly,no,3.0,school_bus,5 - 10,82,90,93
30640,960,male,group B,some college,standard,none,married,never,no,1.0,school_bus,5 - 10,64,60,58

In [10]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 30641 entries, 0 to 30640
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           30641 non-null  int64
 1   Gender               30641 non-null  str
 2   EthnicGroup          28801 non-null  str
 3   ParentEduc           28796 non-null  str
 4   LunchType            30641 non-null  str
 5   TestPrep             28811 non-null  str
 6   ParentMaritalStatus  29451 non-null  str
 7   PracticeSport        30010 non-null  str
 8   IsFirstChild         29737 non-null  str
 9   NrSiblings           29069 non-null  float64
 10  TransportMeans       27507 non-null  str
 11  WklyStudyHours       29686 non-null  str
 12  MathScore            30641 non-null  int64
 13  ReadingScore         30641 non-null  int64
 14  WritingScore         30641 non-null  int64
dtypes: float64(1), int64(4), str(10)
memory usage: 3.5 MB

"""
Deleting redundant columns.
Renaming the columns.
Dropping duplicates.
Remove the NaN values from the dataset
Check for some more Transformations
"""

In [14]:
data = data.drop(columns=['Unnamed: 0', 'TestPrep', 'ParentMaritalStatus',
             'PracticeSport', 'IsFirstChild'])

In [15]:
data.columns

Index(['Gender', 'EthnicGroup', 'ParentEduc', 'LunchType', 'NrSiblings',
       'TransportMeans', 'WklyStudyHours', 'MathScore', 'ReadingScore',
       'WritingScore'],
      dtype='str')

In [16]:
data.columns

,Gender,EthnicGroup,ParentEduc,LunchType,NrSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
0,female,NaN,bachelor's degree,standard,3.0,school_bus,< 5,71,71,74
1,female,group C,some college,standard,0.0,NaN,5 - 10,69,90,88
2,female,group B,master's degree,standard,4.0,school_bus,< 5,87,93,91
3,male,group A,associate's degree,free/reduced,1.0,NaN,5 - 10,45,56,42
4,male,group C,some college,standard,0.0,school_bus,5 - 10,76,78,75
...,...,...,...,...,...,...,...,...,...,...
30636,female,group D,high school,standard,2.0,school_bus,5 - 10,59,61,65
30637,male,group E,high school,standard,1.0,private,5 - 10,58,53,51
30638,female,NaN,high school,free/reduced,1.0,private,5 - 10,61,70,67
30639,female,group D,associate's degree,standard,3.0,school_bus,5 - 10,82,90,93
30640,male,group B,some college,standard,1.0,school_bus,5 - 10,64,60,58

In [17]:
#rename columns
data = data.rename(columns={"Nrsibling":"Number of siblings:"})

In [18]:
data.duplicate().sum()

AttributeError: 'DataFrame' object has no attribute 'duplicate'

In [21]:
data.drop_duplicates(inplace=True )

In [24]:
data.isna().sum().sum ()

np.int64(9345)

In [25]:
data.dropna(inplace=True)

In [26]:
data["Gender"].unique()

<StringArray>
['female', 'male']
Length: 2, dtype: str

In [28]:
data["Gender"] = data["Gender"].apply(lambda x: 1 if x == "female" else 0)

In [29]:
data

,Gender,EthnicGroup,ParentEduc,LunchType,NrSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
2,1,group B,master's degree,standard,4.0,school_bus,< 5,87,93,91
4,0,group C,some college,standard,0.0,school_bus,5 - 10,76,78,75
5,1,group B,associate's degree,standard,1.0,school_bus,5 - 10,73,84,79
6,1,group B,some college,standard,1.0,private,5 - 10,85,93,89
7,0,group B,some college,free/reduced,1.0,private,> 10,41,43,39
...,...,...,...,...,...,...,...,...,...,...
30634,0,group A,associate's degree,free/reduced,2.0,school_bus,5 - 10,65,60,60
30635,0,group C,some college,standard,2.0,school_bus,5 - 10,58,53,49
30636,1,group D,high school,standard,2.0,school_bus,5 - 10,59,61,65
30637,0,group E,high school,standard,1.0,private,5 - 10,58,53,51
30639,1,group D,associate's degree,standard,3.0,school_bus,5 - 10,82,90,93

In [32]:
data.reset_index(drop=True, inplace=True)

In [33]:
data

,Gender,EthnicGroup,ParentEduc,LunchType,NrSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
0,1,group B,master's degree,standard,4.0,school_bus,< 5,87,93,91
1,0,group C,some college,standard,0.0,school_bus,5 - 10,76,78,75
2,1,group B,associate's degree,standard,1.0,school_bus,5 - 10,73,84,79
3,1,group B,some college,standard,1.0,private,5 - 10,85,93,89
4,0,group B,some college,free/reduced,1.0,private,> 10,41,43,39
...,...,...,...,...,...,...,...,...,...,...
22338,0,group A,associate's degree,free/reduced,2.0,school_bus,5 - 10,65,60,60
22339,0,group C,some college,standard,2.0,school_bus,5 - 10,58,53,49
22340,1,group D,high school,standard,2.0,school_bus,5 - 10,59,61,65
22341,0,group E,high school,standard,1.0,private,5 - 10,58,53,51
22342,1,group D,associate's degree,standard,3.0,school_bus,5 - 10,82,90,93

In [36]:
type(data["NrSiblings"][0])

numpy.float64

In [38]:
data["NrSiblings"] = data["NrSiblings"].astype(int)

In [39]:
data

,Gender,EthnicGroup,ParentEduc,LunchType,NrSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
0,1,group B,master's degree,standard,4,school_bus,< 5,87,93,91
1,0,group C,some college,standard,0,school_bus,5 - 10,76,78,75
2,1,group B,associate's degree,standard,1,school_bus,5 - 10,73,84,79
3,1,group B,some college,standard,1,private,5 - 10,85,93,89
4,0,group B,some college,free/reduced,1,private,> 10,41,43,39
...,...,...,...,...,...,...,...,...,...,...
22338,0,group A,associate's degree,free/reduced,2,school_bus,5 - 10,65,60,60
22339,0,group C,some college,standard,2,school_bus,5 - 10,58,53,49
22340,1,group D,high school,standard,2,school_bus,5 - 10,59,61,65
22341,0,group E,high school,standard,1,private,5 - 10,58,53,51
22342,1,group D,associate's degree,standard,3,school_bus,5 - 10,82,90,93

In [40]:
data.to_excel("cleaned_data.xlsx", index=False)

In [41]:
data.to_csv

<bound method NDFrame.to_csv of        Gender EthnicGroup          ParentEduc     LunchType  NrSiblings  \
0           1     group B     master's degree      standard           4
1           0     group C        some college      standard           0
2           1     group B  associate's degree      standard           1
3           1     group B        some college      standard           1
4           0     group B        some college  free/reduced           1
...       ...         ...                 ...           ...         ...
22338       0     group A  associate's degree  free/reduced           2
22339       0     group C        some college      standard           2
22340       1     group D         high school      standard           2
22341       0     group E         high school      standard           1
22342       1     group D  associate's degree      standard           3

      TransportMeans WklyStudyHours  MathScore  ReadingScore  WritingScore
0         school_bus            < 5         87            93            91
1         school_bus         5 - 10         76            78            75
2         school_bus         5 - 10         73            84            79
3            private         5 - 10         85            93            89
4            private           > 10         41            43            39
...              ...            ...        ...           ...           ...
22338     school_bus         5 - 10         65            60            60
22339     school_bus         5 - 10         58            53            49
22340     school_bus         5 - 10         59            61            65
22341        private         5 - 10         58            53            51
22342     school_bus         5 - 10         82            90            93

[22343 rows x 10 columns]>

In [20]:
data.duplicated().sum()

np.int64(9)