In [1]:
import pandas as pd

In [2]:
pd.__version__

'3.0.3'

In [3]:
pd.read_csv('netflix1.csv')

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"
...,...,...,...,...,...,...,...,...,...,...
8785,s8797,TV Show,Yunus Emre,Not Given,Turkey,1/17/2017,2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas"
8786,s8798,TV Show,Zak Storm,Not Given,United States,9/13/2018,2016,TV-Y7,3 Seasons,Kids' TV
8787,s8801,TV Show,Zindagi Gulzar Hai,Not Given,Pakistan,12/15/2016,2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8788,s8784,TV Show,Yoko,Not Given,Pakistan,6/23/2018,2016,TV-Y,1 Season,Kids' TV
8789,s8786,TV Show,YOM,Not Given,Pakistan,6/7/2018,2016,TV-Y7,1 Season,Kids' TV

In [4]:
data = pd.read_csv('netflix1.csv')

In [8]:
data.head(789)

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"
...,...,...,...,...,...,...,...,...,...,...
784,s647,Movie,The House of Flowers: The Movie,Manolo Caro,Mexico,6/23/2021,2021,TV-MA,88 min,"Comedies, International Movies, Music & Musicals"
785,s655,Movie,#Selfie,Cristina Jacob,Romania,6/21/2021,2014,TV-MA,125 min,"Comedies, Dramas, International Movies"
786,s656,Movie,#Selfie 69,Cristina Jacob,Romania,6/21/2021,2016,TV-MA,119 min,"Comedies, Dramas, International Movies"
787,s657,Movie,Love Is a Story,Cristina Jacob,Romania,6/21/2021,2015,TV-MA,105 min,"International Movies, Music & Musicals, Romant..."
788,s645,Movie,Good on Paper,Kimmy Gatewood,Not Given,6/23/2021,2021,TV-MA,94 min,"Comedies, Romantic Movies"

In [9]:
data.tail(20)

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
8770,s8721,TV Show,What Happens to My Family,Not Given,Turkey,5/5/2017,2016,TV-14,1 Season,"International TV Shows, TV Comedies, TV Dramas"
8771,s8593,TV Show,Timeless Season,Not Given,Pakistan,9/18/2017,2009,TV-14,1 Season,"International TV Shows, TV Dramas"
8772,s8722,TV Show,What Is Love?,Not Given,Taiwan,1/1/2017,2012,TV-14,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8773,s8727,TV Show,When Calls the Heart,Not Given,United States,12/29/2018,2017,TV-PG,5 Seasons,TV Dramas
8774,s8737,TV Show,Who's the One,Not Given,Taiwan,1/1/2017,2011,TV-14,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8775,s8741,TV Show,Wild Alaska,Not Given,United Kingdom,3/31/2017,2015,TV-PG,1 Season,"British TV Shows, Docuseries, Science & Nature TV"
8776,s8742,TV Show,Wild Arabia,Not Given,United Kingdom,3/31/2017,2013,TV-PG,1 Season,"British TV Shows, Docuseries, Science & Nature TV"
8777,s8748,TV Show,Winsanity,Not Given,United States,12/15/2018,2016,TV-G,1 Season,Reality TV
8778,s8750,TV Show,Winter Sun,Not Given,Turkey,8/1/2017,2014,TV-MA,1 Season,"International TV Shows, TV Dramas, TV Thrillers"
8779,s8756,TV Show,Women Behind Bars,Not Given,United States,11/1/2016,2010,TV-14,3 Seasons,"Crime TV Shows, Docuseries"
8780,s8759,TV Show,World's Busiest Cities,Not Given,United Kingdom,2/1/2019,2017,TV-PG,1 Season,"British TV Shows, Docuseries"
8781,s8776,TV Show,Yeh Meri Family,Not Given,India,8/31/2018,2018,TV-PG,1 Season,"International TV Shows, TV Comedies"
8782,s8781,TV Show,Yo-Kai Watch,Not Given,United States,4/1/2016,2015,TV-Y7,1 Season,"Anime Series, Kids' TV"
8783,s8785,Movie,Yoko and His Friends,Not Given,Russia,6/23/2018,2015,TV-Y,78 min,Children & Family Movies
8784,s8796,TV Show,Yu-Gi-Oh! Arc-V,Not Given,Japan,5/1/2018,2015,TV-Y7,2 Seasons,"Anime Series, Kids' TV"
8785,s8797,TV Show,Yunus Emre,Not Given,Turkey,1/17/2017,2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas"
8786,s8798,TV Show,Zak Storm,Not Given,United States,9/13/2018,2016,TV-Y7,3 Seasons,Kids' TV
8787,s8801,TV Show,Zindagi Gulzar Hai,Not Given,Pakistan,12/15/2016,2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8788,s8784,TV Show,Yoko,Not Given,Pakistan,6/23/2018,2016,TV-Y,1 Season,Kids' TV
8789,s8786,TV Show,YOM,Not Given,Pakistan,6/7/2018,2016,TV-Y7,1 Season,Kids' TV

In [10]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   str
 1   type          8790 non-null   str
 2   title         8790 non-null   str
 3   director      8790 non-null   str
 4   country       8790 non-null   str
 5   date_added    8790 non-null   str
 6   release_year  8790 non-null   int64
 7   rating        8790 non-null   str
 8   duration      8790 non-null   str
 9   listed_in     8790 non-null   str
dtypes: int64(1), str(9)
memory usage: 686.8 KB

In [ ]:
"""Deleting redundant columns.
Renaming the columns.
Dropping duplicates.
Remove the NaN values from the dataset
Check for some more Transformations"""

In [11]:
data.head(1)

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries

In [12]:
data.columns

Index(['show_id', 'type', 'title', 'director', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in'],
      dtype='str')

In [13]:
data [["rating"]]

     rating
0     PG-13
1     TV-MA
2     TV-MA
3     TV-PG
4     TV-MA
...     ...
8785  TV-PG
8786  TV-Y7
8787  TV-PG
8788   TV-Y
8789  TV-Y7

[8790 rows x 1 columns]

In [19]:
if 'rating' in data.columns:
  data.drop(columns=['rating'], inplace=True)

In [20]:
data.columns

Index(['show_id', 'type', 'title', 'director', 'country', 'date_added',
       'release_year', 'duration', 'listed_in'],
      dtype='str')

In [ ]:
example=

In [23]:
from cmath import pi


new_columns_name=[] 
for i in data.columns :
  new_columns_name.append(i.capitalize())

In [25]:
data.columns=new_columns_name

In [26]:
data.head()

,Show_id,Type,Title,Director,Country,Date_added,Release_year,Duration,Listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,125 min,"Dramas, Independent Movies, International Movies"

In [27]:
data.coulmns = ['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added', 'release_year', 'rating', 'duration', 'listed_in', 'description']

/tmp/ipykernel_28406/3203558861.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  data.coulmns = ['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added', 'release_year', 'rating', 'duration', 'listed_in', 'description']

In [29]:
data.duplicated().sum()

np.int64(0)

In [30]:
#for cleaning dupocate 
data.drop_duplicates(inplace=True)

In [31]:
data.isna

<bound method DataFrame.isna of      Show_id     Type                             Title         Director  \
0         s1    Movie              Dick Johnson Is Dead  Kirsten Johnson
1         s3  TV Show                         Ganglands  Julien Leclercq
2         s6  TV Show                     Midnight Mass    Mike Flanagan
3        s14    Movie  Confessions of an Invisible Girl    Bruno Garotti
4         s8    Movie                           Sankofa     Haile Gerima
...      ...      ...                               ...              ...
8785   s8797  TV Show                        Yunus Emre        Not Given
8786   s8798  TV Show                         Zak Storm        Not Given
8787   s8801  TV Show                Zindagi Gulzar Hai        Not Given
8788   s8784  TV Show                              Yoko        Not Given
8789   s8786  TV Show                               YOM        Not Given

            Country  Date_added  Release_year   Duration  \
0     United States   9/25/2021          2020     90 min
1            France   9/24/2021          2021   1 Season
2     United States   9/24/2021          2021   1 Season
3            Brazil   9/22/2021          2021     91 min
4     United States   9/24/2021          1993    125 min
...             ...         ...           ...        ...
8785         Turkey   1/17/2017          2016  2 Seasons
8786  United States   9/13/2018          2016  3 Seasons
8787       Pakistan  12/15/2016          2012   1 Season
8788       Pakistan   6/23/2018          2016   1 Season
8789       Pakistan    6/7/2018          2016   1 Season

                                              Listed_in
0                                         Documentaries
1     Crime TV Shows, International TV Shows, TV Act...
2                    TV Dramas, TV Horror, TV Mysteries
3                    Children & Family Movies, Comedies
4      Dramas, Independent Movies, International Movies
...                                                 ...
8785                  International TV Shows, TV Dramas
8786                                           Kids' TV
8787  International TV Shows, Romantic TV Shows, TV ...
8788                                           Kids' TV
8789                                           Kids' TV

[8790 rows x 9 columns]>

In [32]:
#if we had na values we can use the following code to remove them
data.dropna(inplace=True)

In [33]:
data.head()

,Show_id,Type,Title,Director,Country,Date_added,Release_year,Duration,Listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,125 min,"Dramas, Independent Movies, International Movies"

In [34]:
data['Show_id'].unique()

<StringArray>
[   's1',    's3',    's6',   's14',    's8',    's9',   's10',  's939',
   's13',  's940',
 ...
 's8759', 's8776', 's8781', 's8785', 's8796', 's8797', 's8798', 's8801',
 's8784', 's8786']
Length: 8790, dtype: str

In [43]:
if isinstance(data, pd.DataFrame):
  data["Show_id"] = data["Show_id"].astype(str).str.split("s").str[1]
else:
  data = data.astype(str).str.split("s").str[1]

In [54]:
type(data["Show_id	"][0])

KeyError: 'Show_id\t'

In [ ]:
"/" "-"

In [58]:
col = 'Date_added' if 'Date_added' in data.columns else 'date_added'
data[col] = data[col].astype(str).str.replace("/", "-", regex=False)

AttributeError: 'Series' object has no attribute 'columns'

In [59]:
data.to_csv('netflix_cleaned.csv', index=False)

In [62]:
data.to_excel('netflix_cleaned.xlsx', index=False)

In [48]:
data["Show_id"] = data["Show_id"].astype(int)

KeyError: 'Show_id'

In [39]:
data

0          1
1          3
2          6
3         14
4          8
        ...
8785    8797
8786    8798
8787    8801
8788    8784
8789    8786
Name: Show_id, Length: 8790, dtype: str

In [24]:
new_columns_name

['Show_id',
 'Type',
 'Title',
 'Director',
 'Country',
 'Date_added',
 'Release_year',
 'Duration',
 'Listed_in']