In [2]:
import pandas as pd

In [4]:
data=pd.read_csv('credit_customers.csv')

In [5]:
data

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,<0,6.0,critical/other existing credit,radio/tv,1169.0,no known savings,>=7,4.0,male single,none,...,real estate,67.0,none,own,2.0,skilled,1.0,yes,yes,good
1,0<=X<200,48.0,existing paid,radio/tv,5951.0,<100,1<=X<4,2.0,female div/dep/mar,none,...,real estate,22.0,none,own,1.0,skilled,1.0,none,yes,bad
2,no checking,12.0,critical/other existing credit,education,2096.0,<100,4<=X<7,2.0,male single,none,...,real estate,49.0,none,own,1.0,unskilled resident,2.0,none,yes,good
3,<0,42.0,existing paid,furniture/equipment,7882.0,<100,4<=X<7,2.0,male single,guarantor,...,life insurance,45.0,none,for free,1.0,skilled,2.0,none,yes,good
4,<0,24.0,delayed previously,new car,4870.0,<100,1<=X<4,3.0,male single,none,...,no known property,53.0,none,for free,2.0,skilled,2.0,none,yes,bad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,no checking,12.0,existing paid,furniture/equipment,1736.0,<100,4<=X<7,3.0,female div/dep/mar,none,...,real estate,31.0,none,own,1.0,unskilled resident,1.0,none,yes,good
996,<0,30.0,existing paid,used car,3857.0,<100,1<=X<4,4.0,male div/sep,none,...,life insurance,40.0,none,own,1.0,high qualif/self emp/mgmt,1.0,yes,yes,good
997,no checking,12.0,existing paid,radio/tv,804.0,<100,>=7,4.0,male single,none,...,car,38.0,none,own,1.0,skilled,1.0,none,yes,good
998,<0,45.0,existing paid,radio/tv,1845.0,<100,1<=X<4,4.0,male single,none,...,no known property,23.0,none,for free,1.0,skilled,1.0,yes,yes,bad
999,0<=X<200,45.0,critical/other existing credit,used car,4576.0,100<=X<500,unemployed,3.0,male single,none,...,car,27.0,none,own,1.0,skilled,1.0,none,yes,good

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   checking_status         1000 non-null   str
 1   duration                1000 non-null   float64
 2   credit_history          1000 non-null   str
 3   purpose                 1000 non-null   str
 4   credit_amount           1000 non-null   float64
 5   savings_status          1000 non-null   str
 6   employment              1000 non-null   str
 7   installment_commitment  1000 non-null   float64
 8   personal_status         1000 non-null   str
 9   other_parties           1000 non-null   str
 10  residence_since         1000 non-null   float64
 11  property_magnitude      1000 non-null   str
 12  age                     1000 non-null   float64
 13  other_payment_plans     1000 non-null   str
 14  housing                 1000 non-null   str
 15  existing_credits        1000 non-null   float64
 16  job                     1000 non-null   str
 17  num_dependents          1000 non-null   float64
 18  own_telephone           1000 non-null   str
 19  foreign_worker          1000 non-null   str
 20  class                   1000 non-null   str
dtypes: float64(7), str(14)
memory usage: 164.2 KB

In [7]:
data.columns

Index(['checking_status', 'duration', 'credit_history', 'purpose',
       'credit_amount', 'savings_status', 'employment',
       'installment_commitment', 'personal_status', 'other_parties',
       'residence_since', 'property_magnitude', 'age', 'other_payment_plans',
       'housing', 'existing_credits', 'job', 'num_dependents', 'own_telephone',
       'foreign_worker', 'class'],
      dtype='str')

In [10]:
data.head(1)

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,<0,6.0,critical/other existing credit,radio/tv,1169.0,no known savings,>=7,4.0,male single,none,...,real estate,67.0,none,own,2.0,skilled,1.0,yes,yes,good

In [13]:
data .drop(columns=['checking_status', 'duration', 'credit_history', 'purpose', 'employment',
                    'installment_commitment', 'personal_status', 'other_parties',
                    'residence_since', 'property_magnitude', 'other_payment_plans', 'num_dependents' ],inplace=True)

In [14]:
data.columns

Index(['credit_amount', 'savings_status', 'age', 'housing', 'existing_credits',
       'job', 'own_telephone', 'foreign_worker', 'class'],
      dtype='str')

In [17]:
data.drop(columns=["savings_status"], inplace=True, errors="ignore")

In [18]:
example="string example"

In [19]:
example.capitalize()

'String example'

In [22]:
data.columns

Index(['credit_amount', 'age', 'housing', 'existing_credits', 'job',
       'own_telephone', 'foreign_worker', 'class'],
      dtype='str')

In [23]:
data.columns=data_new_columns

In [24]:
data_new_columns

['Credit_amount',
 'Age',
 'Housing',
 'Existing_credits',
 'Job',
 'Own_telephone',
 'Foreign_worker',
 'Class']

In [25]:
data.duplicated().sum()

np.int64(0)

In [26]:
data.drop_duplicates(inplace=True)

In [29]:
data.isna().sum()

Credit_amount       0
Age                 0
Housing             0
Existing_credits    0
Job                 0
Own_telephone       0
Foreign_worker      0
Class               0
dtype: int64

In [30]:
data.dropna(inplace= True)

In [31]:
data

,Credit_amount,Age,Housing,Existing_credits,Job,Own_telephone,Foreign_worker,Class
0,1169.0,67.0,own,2.0,skilled,yes,yes,good
1,5951.0,22.0,own,1.0,skilled,none,yes,bad
2,2096.0,49.0,own,1.0,unskilled resident,none,yes,good
3,7882.0,45.0,for free,1.0,skilled,none,yes,good
4,4870.0,53.0,for free,2.0,skilled,none,yes,bad
...,...,...,...,...,...,...,...,...
995,1736.0,31.0,own,1.0,unskilled resident,none,yes,good
996,3857.0,40.0,own,1.0,high qualif/self emp/mgmt,yes,yes,good
997,804.0,38.0,own,1.0,skilled,none,yes,good
998,1845.0,23.0,for free,1.0,skilled,yes,yes,bad
999,4576.0,27.0,own,1.0,skilled,none,yes,good

In [32]:
data["Class"].unique()

<StringArray>
['good', 'bad']
Length: 2, dtype: str

In [34]:
data["Class"] = data["Class"].apply(lambda x:1 if x == "good" else 0)

In [35]:
data

,Credit_amount,Age,Housing,Existing_credits,Job,Own_telephone,Foreign_worker,Class
0,1169.0,67.0,own,2.0,skilled,yes,yes,1
1,5951.0,22.0,own,1.0,skilled,none,yes,0
2,2096.0,49.0,own,1.0,unskilled resident,none,yes,1
3,7882.0,45.0,for free,1.0,skilled,none,yes,1
4,4870.0,53.0,for free,2.0,skilled,none,yes,0
...,...,...,...,...,...,...,...,...
995,1736.0,31.0,own,1.0,unskilled resident,none,yes,1
996,3857.0,40.0,own,1.0,high qualif/self emp/mgmt,yes,yes,1
997,804.0,38.0,own,1.0,skilled,none,yes,1
998,1845.0,23.0,for free,1.0,skilled,yes,yes,0
999,4576.0,27.0,own,1.0,skilled,none,yes,1

In [36]:
type (data["Class"])

pandas.Series

In [38]:
data.columns = data.columns.str.strip()
type(data["Existing_credits"][0])

numpy.float64

In [40]:
data["Existing_credits"].unique()

<bound method Series.unique of 0      2.0
1      1.0
2      1.0
3      1.0
4      2.0
      ...
995    1.0
996    1.0
997    1.0
998    1.0
999    1.0
Name: Existing_credits, Length: 1000, dtype: float64>

In [47]:
data["Existing_credits"] = data["Existing_credits"].astype(int)

In [48]:
data.to_excel("cleaned_data.xlsx", index=False)

In [49]:
data.to_csv("cleaned_data.csv", index=False)

In [21]:
data_new_columns = []
for i in data.columns:
     data_new_columns.append(i.capitalize())