In [5]:
import pandas as pd

In [6]:
data = pd.read_csv("onlinefoods.csv")

In [8]:
data .head(2)

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,latitude,longitude,Pin code,Output,Feedback,Unnamed: 12
0,20,Female,Single,Student,No Income,Post Graduate,4,12.9766,77.5993,560001,Yes,Positive,Yes
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,12.9770,77.5773,560009,Yes,Positive,Yes

In [9]:
type(data["latitude"][1])

np.float64(12.977)

In [10]:
data.shape

(388, 13)

In [12]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 388 entries, 0 to 387
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         388 non-null    int64
 1   Gender                      388 non-null    str
 2   Marital Status              388 non-null    str
 3   Occupation                  388 non-null    str
 4   Monthly Income              388 non-null    str
 5   Educational Qualifications  388 non-null    str
 6   Family size                 388 non-null    int64
 7   latitude                    388 non-null    float64
 8   longitude                   388 non-null    float64
 9   Pin code                    388 non-null    int64
 10  Output                      388 non-null    str
 11  Feedback                    388 non-null    str
 12  Unnamed: 12                 388 non-null    str
dtypes: float64(2), int64(3), str(8)
memory usage: 39.5 KB

In [ ]:
"""
Deleting redundant columns.
Renaming the columns.
Dropping duplicates.
Remove the NaN values from the dataset
Check for some more Transformations
"""

In [13]:
data.columns

Index(['Age', 'Gender', 'Marital Status', 'Occupation', 'Monthly Income',
       'Educational Qualifications', 'Family size', 'latitude', 'longitude',
       'Pin code', 'Output', 'Feedback', 'Unnamed: 12'],
      dtype='str')

In [ ]:
data_to_keep = ['Age', 'Gender', 'Marital Status', 'Occupation', 'Monthly Income',
                'Educational Qualifications', 'Family size']
data_to_drop = ['latitude', 'longitude',
                'Pin code', 'Unnamed: 12']

In [16]:
try:
  print(len(data_to_keep))
except NameError:
  data_to_keep = ['Age', 'Gender', 'Marital Status', 'Occupation', 'Monthly Income',
          'Educational Qualifications', 'Family size']
  print(len(data_to_keep))

7

In [18]:
try:
  print(len(data_to_drop))
except NameError:
  data_to_drop = ['latitude', 'longitude', 'Pin code', 'Unnamed: 12']
  print(len(data_to_drop))

4

In [19]:
data

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,latitude,longitude,Pin code,Output,Feedback,Unnamed: 12
0,20,Female,Single,Student,No Income,Post Graduate,4,12.9766,77.5993,560001,Yes,Positive,Yes
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,12.9770,77.5773,560009,Yes,Positive,Yes
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,12.9551,77.6593,560017,Yes,Negative,Yes
3,22,Female,Single,Student,No Income,Graduate,6,12.9473,77.5616,560019,Yes,Positive,Yes
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,12.9850,77.5533,560010,Yes,Positive,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...
383,23,Female,Single,Student,No Income,Post Graduate,2,12.9766,77.5993,560001,Yes,Positive,Yes
384,23,Female,Single,Student,No Income,Post Graduate,4,12.9854,77.7081,560048,Yes,Positive,Yes
385,22,Female,Single,Student,No Income,Post Graduate,5,12.9850,77.5533,560010,Yes,Positive,Yes
386,23,Male,Single,Student,Below Rs.10000,Post Graduate,2,12.9770,77.5773,560009,Yes,Positive,Yes
387,23,Male,Single,Student,No Income,Post Graduate,5,12.8988,77.5764,560078,Yes,Positive,Yes

# filttering columns the we wnated

In [25]:
data = pd.read_csv("onlinefoods.csv")
data["Age"]

0      20
1      24
2      22
3      22
4      22
       ..
383    23
384    23
385    22
386    23
387    23
Name: Age, Length: 388, dtype: int64

In [30]:
data[data_to_keep]

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size
0,20,Female,Single,Student,No Income,Post Graduate,4
1,24,Female,Single,Student,Below Rs.10000,Graduate,3
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3
3,22,Female,Single,Student,No Income,Graduate,6
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4
...,...,...,...,...,...,...,...
383,23,Female,Single,Student,No Income,Post Graduate,2
384,23,Female,Single,Student,No Income,Post Graduate,4
385,22,Female,Single,Student,No Income,Post Graduate,5
386,23,Male,Single,Student,Below Rs.10000,Post Graduate,2
387,23,Male,Single,Student,No Income,Post Graduate,5

In [31]:
modified_data = data[data_to_keep]

In [32]:
modified_data

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size
0,20,Female,Single,Student,No Income,Post Graduate,4
1,24,Female,Single,Student,Below Rs.10000,Graduate,3
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3
3,22,Female,Single,Student,No Income,Graduate,6
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4
...,...,...,...,...,...,...,...
383,23,Female,Single,Student,No Income,Post Graduate,2
384,23,Female,Single,Student,No Income,Post Graduate,4
385,22,Female,Single,Student,No Income,Post Graduate,5
386,23,Male,Single,Student,Below Rs.10000,Post Graduate,2
387,23,Male,Single,Student,No Income,Post Graduate,5

# 2nd way ,droping the unccessaty

In [34]:
data.drop(columns=[col for col in data_to_drop if col in data.columns], inplace=True)

In [35]:
data

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size
0,20,Female,Single,Student,No Income,Post Graduate,4
1,24,Female,Single,Student,Below Rs.10000,Graduate,3
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3
3,22,Female,Single,Student,No Income,Graduate,6
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4
...,...,...,...,...,...,...,...
383,23,Female,Single,Student,No Income,Post Graduate,2
384,23,Female,Single,Student,No Income,Post Graduate,4
385,22,Female,Single,Student,No Income,Post Graduate,5
386,23,Male,Single,Student,Below Rs.10000,Post Graduate,2
387,23,Male,Single,Student,No Income,Post Graduate,5

In [29]:
data.columns

Index(['Age', 'Gender', 'Marital Status', 'Occupation', 'Monthly Income',
       'Educational Qualifications', 'Family size'],
      dtype='str')

# reaniming columns

In [40]:
data.rename(columns={"Monthly Income ": "Monthly salary"}, inplace=True)

In [41]:
data

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size
0,20,Female,Single,Student,No Income,Post Graduate,4
1,24,Female,Single,Student,Below Rs.10000,Graduate,3
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3
3,22,Female,Single,Student,No Income,Graduate,6
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4
...,...,...,...,...,...,...,...
383,23,Female,Single,Student,No Income,Post Graduate,2
384,23,Female,Single,Student,No Income,Post Graduate,4
385,22,Female,Single,Student,No Income,Post Graduate,5
386,23,Male,Single,Student,Below Rs.10000,Post Graduate,2
387,23,Male,Single,Student,No Income,Post Graduate,5

In [45]:
data.duplicated().sum()

np.int64(159)

In [46]:
data.drop_duplicates(inplace=True)

In [47]:
data.duplicated().sum()

np.int64(0)

In [48]:
data.isna().sum()

Age                           0
Gender                        0
Marital Status                0
Occupation                    0
Monthly Income                0
Educational Qualifications    0
Family size                   0
dtype: int64

In [49]:
data.dropna(inplace=True)

In [50]:
data.isna().sum()

Age                           0
Gender                        0
Marital Status                0
Occupation                    0
Monthly Income                0
Educational Qualifications    0
Family size                   0
dtype: int64

In [51]:
data

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size
0,20,Female,Single,Student,No Income,Post Graduate,4
1,24,Female,Single,Student,Below Rs.10000,Graduate,3
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3
3,22,Female,Single,Student,No Income,Graduate,6
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4
...,...,...,...,...,...,...,...
299,25,Female,Single,Employee,More than 50000,Post Graduate,6
321,21,Male,Married,Employee,More than 50000,Ph.D,3
342,22,Male,Married,Self Employeed,10001 to 25000,School,3
363,31,Male,Married,Employee,More than 50000,Ph.D,3
369,30,Male,Married,Employee,More than 50000,Post Graduate,6

In [52]:
data[ "Age {Months}"] =data ["Age"]*12

In [55]:
data["Gender"].apply (lambda x :"F" if x == " Female" else "M")

0      M
1      M
2      M
3      M
4      M
      ..
299    M
321    M
342    M
363    M
369    M
Name: Gender, Length: 229, dtype: str

In [56]:
data

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,Age {Months}
0,20,Female,Single,Student,No Income,Post Graduate,4,240
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,288
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,264
3,22,Female,Single,Student,No Income,Graduate,6,264
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,264
...,...,...,...,...,...,...,...,...
299,25,Female,Single,Employee,More than 50000,Post Graduate,6,300
321,21,Male,Married,Employee,More than 50000,Ph.D,3,252
342,22,Male,Married,Self Employeed,10001 to 25000,School,3,264
363,31,Male,Married,Employee,More than 50000,Ph.D,3,372
369,30,Male,Married,Employee,More than 50000,Post Graduate,6,360

In [57]:
data.head(2)

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,Age {Months}
0,20,Female,Single,Student,No Income,Post Graduate,4,240
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,288

In [58]:
data ["Family size"] = data ["Family size"].apply(lambda x : "large" if x > 3 else " small ")

In [59]:
data

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,Age {Months}
0,20,Female,Single,Student,No Income,Post Graduate,large,240
1,24,Female,Single,Student,Below Rs.10000,Graduate,small,288
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,small,264
3,22,Female,Single,Student,No Income,Graduate,large,264
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,large,264
...,...,...,...,...,...,...,...,...
299,25,Female,Single,Employee,More than 50000,Post Graduate,large,300
321,21,Male,Married,Employee,More than 50000,Ph.D,small,252
342,22,Male,Married,Self Employeed,10001 to 25000,School,small,264
363,31,Male,Married,Employee,More than 50000,Ph.D,small,372
369,30,Male,Married,Employee,More than 50000,Post Graduate,large,360

In [65]:
# First, check if 'Output' column exists
if 'Output' in data.columns:
  data["Output"] = data["Output"].apply(lambda x: 1 if str(x).strip().lower() == "yes" else 0)
else:
  print("'Output' column not found. Available columns are:")
  print(data.columns.tolist())

'Output' column not found. Available columns are:
['Age', 'Gender', 'Marital Status', 'Occupation', 'Monthly Income', 'Educational Qualifications', 'Family size', 'Age {Months}']

In [68]:
if 'Output' in data.columns:
  data['Output'] = data['Output'].astype(float)
else:
  print("'Output' column not found. Available columns are:")
  print(data.columns.tolist())

'Output' column not found. Available columns are:
['Age', 'Gender', 'Marital Status', 'Occupation', 'Monthly Income', 'Educational Qualifications', 'Family size', 'Age {Months}']

In [69]:
data

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,Age {Months}
0,20,Female,Single,Student,No Income,Post Graduate,large,240
1,24,Female,Single,Student,Below Rs.10000,Graduate,small,288
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,small,264
3,22,Female,Single,Student,No Income,Graduate,large,264
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,large,264
...,...,...,...,...,...,...,...,...
299,25,Female,Single,Employee,More than 50000,Post Graduate,large,300
321,21,Male,Married,Employee,More than 50000,Ph.D,small,252
342,22,Male,Married,Self Employeed,10001 to 25000,School,small,264
363,31,Male,Married,Employee,More than 50000,Ph.D,small,372
369,30,Male,Married,Employee,More than 50000,Post Graduate,large,360

In [70]:
data .to_excel("Online_Food_cleaned.xlsx", index=False)

In [71]:
data. to_csv("Online_Food_cleaned.csv", index=False)

In [73]:
data = data.reset_index(drop=True)

In [74]:
data

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,Age {Months}
0,20,Female,Single,Student,No Income,Post Graduate,large,240
1,24,Female,Single,Student,Below Rs.10000,Graduate,small,288
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,small,264
3,22,Female,Single,Student,No Income,Graduate,large,264
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,large,264
...,...,...,...,...,...,...,...,...
224,25,Female,Single,Employee,More than 50000,Post Graduate,large,300
225,21,Male,Married,Employee,More than 50000,Ph.D,small,252
226,22,Male,Married,Self Employeed,10001 to 25000,School,small,264
227,31,Male,Married,Employee,More than 50000,Ph.D,small,372
228,30,Male,Married,Employee,More than 50000,Post Graduate,large,360